events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # 1. Cấu hình Frontend
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location /static/ {
            alias /usr/share/nginx/html/static/;
            expires 30d;
        }

        # 2. API Auth (Dịch vụ xác thực - Port 4001)
        location /api/auth/ {
            proxy_pass http://auth_service:4001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            # Quan trọng: Cho phép truyền Token qua header
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
        }

        # 3. API Room (Xem danh sách phòng - Port 4002)
        location /api/room/ {
            proxy_pass http://room_service:4002/;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
        }

        # 4. API Booking (Đặt phòng & Lịch sử - Port 4005)
        location /api/booking/ {
            proxy_pass http://booking_service:4005/;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
        }

        # 5. API Payment (Thanh toán - Port 4003)
        location /api/payment/ {
            proxy_pass http://payment_service:4003/;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
        }
    }
}